include: package:lints/recommended.yaml

linter:
  rules:
    - package_api_docs
    - public_member_api_docs
    - sort_pub_dependencies
    - lines_longer_than_80_chars
    - sort_constructors_first
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_return: error
    missing_required_param: error
  exclude:
    - 'build/**'
    - '**/*.g.dart'
