name: shape_starter_kit
description: A set of generic and commonly used form fields and functions for
  use with the shape package.
version: 0.0.1
repository: https://github.com/betterment/shape/tree/main/packages/shape_generator

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  equatable: ^2.0.2
  meta: ^1.9.1
  shape:
    path: ../shape

dev_dependencies:
  checks: ^0.2.2
  lints: ^2.1.1
  test: ^1.24.5
