name: shape
description: A package for building forms that can be easily reused, validated,
  and parsed, primarily for Flutter apps.
version: 0.0.1
repository: https://github.com/betterment/shape/tree/main/packages/shape

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  equatable: ^2.0.2
  meta: ^1.9.1

dev_dependencies:
  checks: ^0.3.1
  lints: ^5.1.1
  test: ^1.26.2
