name: forms_generator
description: A forms code generator for in the Betterment application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  equatable: ^2.0.2
  forms:
    path: ../forms
  lints: ^2.1.1
  meta: ^1.9.1
  source_gen: ^1.4.0

dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.5
  mocktail: ^0.3.0
