targets:
  $default:
    builders:
      shape_generator|shape:
        enabled: true

builders:
  shape:
    target: ":shape_generator"
    import: "package:shape_generator/builder.dart"
    builder_factories: ["shape"]
    build_extensions: { ".dart": [".shape.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
