name: shape_generator
description: The code generator for the shape package.
version: 0.0.1
repository: https://github.com/betterment/shape/tree/main/packages/shape_generator

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  equatable: ^2.0.2
  meta: ^1.9.1
  path: ^1.8.3
  shape: ^0.0.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.5
  checks: ^0.2.2
  lints: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.5
