name: shape_generator
description: The code generator for the shape package. For more information,
  check out the README of the shape package.
version: 0.0.2
repository: https://github.com/betterment/shape/tree/main/packages/shape_generator

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  analyzer: ">=5.12.0"
  build: ^2.4.1
  equatable: ^2.0.2
  meta: ^1.9.1
  path: ^1.8.3
  shape: ^0.0.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  checks: ^0.3.1
  lints: ^5.1.1
  mocktail: ^0.3.0
  test: ^1.26.2
